#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Northwind.Data;

namespace Northwind.Data	
{
	public partial class NorthwindModel : OpenAccessContext, INorthwindModelUnitOfWork
	{
		private static string connectionStringName = @"NorthwindConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("NorthwindModel.rlinq");
		
		public NorthwindModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public NorthwindModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public NorthwindModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public NorthwindModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public NorthwindModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Territory> Territories 
		{
			get
			{
				return this.GetAll<Territory>();
			}
		}
		
		public IQueryable<Supplier> Suppliers 
		{
			get
			{
				return this.GetAll<Supplier>();
			}
		}
		
		public IQueryable<Shipper> Shippers 
		{
			get
			{
				return this.GetAll<Shipper>();
			}
		}
		
		public IQueryable<Region> Regions 
		{
			get
			{
				return this.GetAll<Region>();
			}
		}
		
		public IQueryable<Product> Products 
		{
			get
			{
				return this.GetAll<Product>();
			}
		}
		
		public IQueryable<Order> Orders 
		{
			get
			{
				return this.GetAll<Order>();
			}
		}
		
		public IQueryable<OrderDetail> OrderDetails 
		{
			get
			{
				return this.GetAll<OrderDetail>();
			}
		}
		
		public IQueryable<Employee> Employees 
		{
			get
			{
				return this.GetAll<Employee>();
			}
		}
		
		public IQueryable<Customer> Customers 
		{
			get
			{
				return this.GetAll<Customer>();
			}
		}
		
		public IQueryable<CustomerDemographic> CustomerDemographics 
		{
			get
			{
				return this.GetAll<CustomerDemographic>();
			}
		}
		
		public IQueryable<Category> Categories 
		{
			get
			{
				return this.GetAll<Category>();
			}
		}
		
		public IQueryable<SummaryOfSalesByYear> SummaryOfSalesByYears 
		{
			get
			{
				return this.GetAll<SummaryOfSalesByYear>();
			}
		}
		
		public IQueryable<SummaryOfSalesByQuarter> SummaryOfSalesByQuarters 
		{
			get
			{
				return this.GetAll<SummaryOfSalesByQuarter>();
			}
		}
		
		public IQueryable<SalesTotalsByAmount> SalesTotalsByAmounts 
		{
			get
			{
				return this.GetAll<SalesTotalsByAmount>();
			}
		}
		
		public IQueryable<SalesByCategory> SalesByCategories 
		{
			get
			{
				return this.GetAll<SalesByCategory>();
			}
		}
		
		public IQueryable<QuarterlyOrder> QuarterlyOrders 
		{
			get
			{
				return this.GetAll<QuarterlyOrder>();
			}
		}
		
		public IQueryable<ProductsByCategory> ProductsByCategories 
		{
			get
			{
				return this.GetAll<ProductsByCategory>();
			}
		}
		
		public IQueryable<ProductsAboveAveragePrice> ProductsAboveAveragePrices 
		{
			get
			{
				return this.GetAll<ProductsAboveAveragePrice>();
			}
		}
		
		public IQueryable<ProductSalesFor1997> ProductSalesFor1997 
		{
			get
			{
				return this.GetAll<ProductSalesFor1997>();
			}
		}
		
		public IQueryable<OrdersQry> OrdersQries 
		{
			get
			{
				return this.GetAll<OrdersQry>();
			}
		}
		
		public IQueryable<OrderSubtotal> OrderSubtotals 
		{
			get
			{
				return this.GetAll<OrderSubtotal>();
			}
		}
		
		public IQueryable<OrderDetailsExtended> OrderDetailsExtendeds 
		{
			get
			{
				return this.GetAll<OrderDetailsExtended>();
			}
		}
		
		public IQueryable<Invoice> Invoices 
		{
			get
			{
				return this.GetAll<Invoice>();
			}
		}
		
		public IQueryable<CustomerAndSuppliersByCity> CustomerAndSuppliersByCities 
		{
			get
			{
				return this.GetAll<CustomerAndSuppliersByCity>();
			}
		}
		
		public IQueryable<CurrentProductList> CurrentProductLists 
		{
			get
			{
				return this.GetAll<CurrentProductList>();
			}
		}
		
		public IQueryable<CategorySalesFor1997> CategorySalesFor1997 
		{
			get
			{
				return this.GetAll<CategorySalesFor1997>();
			}
		}
		
		public IQueryable<AlphabeticalListOfProduct> AlphabeticalListOfProducts 
		{
			get
			{
				return this.GetAll<AlphabeticalListOfProduct>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
			return backend;
		}
	}
	
	public interface INorthwindModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Territory> Territories
		{
			get;
		}
		IQueryable<Supplier> Suppliers
		{
			get;
		}
		IQueryable<Shipper> Shippers
		{
			get;
		}
		IQueryable<Region> Regions
		{
			get;
		}
		IQueryable<Product> Products
		{
			get;
		}
		IQueryable<Order> Orders
		{
			get;
		}
		IQueryable<OrderDetail> OrderDetails
		{
			get;
		}
		IQueryable<Employee> Employees
		{
			get;
		}
		IQueryable<Customer> Customers
		{
			get;
		}
		IQueryable<CustomerDemographic> CustomerDemographics
		{
			get;
		}
		IQueryable<Category> Categories
		{
			get;
		}
		IQueryable<SummaryOfSalesByYear> SummaryOfSalesByYears
		{
			get;
		}
		IQueryable<SummaryOfSalesByQuarter> SummaryOfSalesByQuarters
		{
			get;
		}
		IQueryable<SalesTotalsByAmount> SalesTotalsByAmounts
		{
			get;
		}
		IQueryable<SalesByCategory> SalesByCategories
		{
			get;
		}
		IQueryable<QuarterlyOrder> QuarterlyOrders
		{
			get;
		}
		IQueryable<ProductsByCategory> ProductsByCategories
		{
			get;
		}
		IQueryable<ProductsAboveAveragePrice> ProductsAboveAveragePrices
		{
			get;
		}
		IQueryable<ProductSalesFor1997> ProductSalesFor1997
		{
			get;
		}
		IQueryable<OrdersQry> OrdersQries
		{
			get;
		}
		IQueryable<OrderSubtotal> OrderSubtotals
		{
			get;
		}
		IQueryable<OrderDetailsExtended> OrderDetailsExtendeds
		{
			get;
		}
		IQueryable<Invoice> Invoices
		{
			get;
		}
		IQueryable<CustomerAndSuppliersByCity> CustomerAndSuppliersByCities
		{
			get;
		}
		IQueryable<CurrentProductList> CurrentProductLists
		{
			get;
		}
		IQueryable<CategorySalesFor1997> CategorySalesFor1997
		{
			get;
		}
		IQueryable<AlphabeticalListOfProduct> AlphabeticalListOfProducts
		{
			get;
		}
	}
}
namespace Northwind.Data	
{
	public partial class Territory
	{
		private string _territoryID;
		public virtual string TerritoryID
		{
			get
			{
				return this._territoryID;
			}
			set
			{
				this._territoryID = value;
			}
		}
		
		private string _territoryDescription;
		public virtual string TerritoryDescription
		{
			get
			{
				return this._territoryDescription;
			}
			set
			{
				this._territoryDescription = value;
			}
		}
		
		private int _regionID;
		public virtual int RegionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				this._regionID = value;
			}
		}
		
		private Region _region;
		public virtual Region Region
		{
			get
			{
				return this._region;
			}
			set
			{
				this._region = value;
			}
		}
		
		private IList<Employee> _employees = new List<Employee>();
		public virtual IList<Employee> Employees
		{
			get
			{
				return this._employees;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class Supplier
	{
		private int _supplierID;
		public virtual int SupplierID
		{
			get
			{
				return this._supplierID;
			}
			set
			{
				this._supplierID = value;
			}
		}
		
		private string _companyName;
		public virtual string CompanyName
		{
			get
			{
				return this._companyName;
			}
			set
			{
				this._companyName = value;
			}
		}
		
		private string _contactName;
		public virtual string ContactName
		{
			get
			{
				return this._contactName;
			}
			set
			{
				this._contactName = value;
			}
		}
		
		private string _contactTitle;
		public virtual string ContactTitle
		{
			get
			{
				return this._contactTitle;
			}
			set
			{
				this._contactTitle = value;
			}
		}
		
		private string _address;
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
		private string _region;
		public virtual string Region
		{
			get
			{
				return this._region;
			}
			set
			{
				this._region = value;
			}
		}
		
		private string _postalCode;
		public virtual string PostalCode
		{
			get
			{
				return this._postalCode;
			}
			set
			{
				this._postalCode = value;
			}
		}
		
		private string _country;
		public virtual string Country
		{
			get
			{
				return this._country;
			}
			set
			{
				this._country = value;
			}
		}
		
		private string _phone;
		public virtual string Phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				this._phone = value;
			}
		}
		
		private string _fax;
		public virtual string Fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				this._fax = value;
			}
		}
		
		private string _homePage;
		public virtual string HomePage
		{
			get
			{
				return this._homePage;
			}
			set
			{
				this._homePage = value;
			}
		}
		
		private IList<Product> _products = new List<Product>();
		public virtual IList<Product> Products
		{
			get
			{
				return this._products;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class Shipper
	{
		private int _shipperID;
		public virtual int ShipperID
		{
			get
			{
				return this._shipperID;
			}
			set
			{
				this._shipperID = value;
			}
		}
		
		private string _companyName;
		public virtual string CompanyName
		{
			get
			{
				return this._companyName;
			}
			set
			{
				this._companyName = value;
			}
		}
		
		private string _phone;
		public virtual string Phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				this._phone = value;
			}
		}
		
		private IList<Order> _orders = new List<Order>();
		public virtual IList<Order> Orders
		{
			get
			{
				return this._orders;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class Region
	{
		private int _regionID;
		public virtual int RegionID
		{
			get
			{
				return this._regionID;
			}
			set
			{
				this._regionID = value;
			}
		}
		
		private string _regionDescription;
		public virtual string RegionDescription
		{
			get
			{
				return this._regionDescription;
			}
			set
			{
				this._regionDescription = value;
			}
		}
		
		private IList<Territory> _territories = new List<Territory>();
		public virtual IList<Territory> Territories
		{
			get
			{
				return this._territories;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class Product
	{
		private int _productID;
		public virtual int ProductID
		{
			get
			{
				return this._productID;
			}
			set
			{
				this._productID = value;
			}
		}
		
		private string _productName;
		public virtual string ProductName
		{
			get
			{
				return this._productName;
			}
			set
			{
				this._productName = value;
			}
		}
		
		private int? _supplierID;
		public virtual int? SupplierID
		{
			get
			{
				return this._supplierID;
			}
			set
			{
				this._supplierID = value;
			}
		}
		
		private int? _categoryID;
		public virtual int? CategoryID
		{
			get
			{
				return this._categoryID;
			}
			set
			{
				this._categoryID = value;
			}
		}
		
		private string _quantityPerUnit;
		public virtual string QuantityPerUnit
		{
			get
			{
				return this._quantityPerUnit;
			}
			set
			{
				this._quantityPerUnit = value;
			}
		}
		
		private decimal? _unitPrice;
		public virtual decimal? UnitPrice
		{
			get
			{
				return this._unitPrice;
			}
			set
			{
				this._unitPrice = value;
			}
		}
		
		private short? _unitsInStock;
		public virtual short? UnitsInStock
		{
			get
			{
				return this._unitsInStock;
			}
			set
			{
				this._unitsInStock = value;
			}
		}
		
		private short? _unitsOnOrder;
		public virtual short? UnitsOnOrder
		{
			get
			{
				return this._unitsOnOrder;
			}
			set
			{
				this._unitsOnOrder = value;
			}
		}
		
		private short? _reorderLevel;
		public virtual short? ReorderLevel
		{
			get
			{
				return this._reorderLevel;
			}
			set
			{
				this._reorderLevel = value;
			}
		}
		
		private bool _discontinued;
		public virtual bool Discontinued
		{
			get
			{
				return this._discontinued;
			}
			set
			{
				this._discontinued = value;
			}
		}
		
		private Category _category;
		public virtual Category Category
		{
			get
			{
				return this._category;
			}
			set
			{
				this._category = value;
			}
		}
		
		private Supplier _supplier;
		public virtual Supplier Supplier
		{
			get
			{
				return this._supplier;
			}
			set
			{
				this._supplier = value;
			}
		}
		
		private IList<OrderDetail> _orderDetails = new List<OrderDetail>();
		public virtual IList<OrderDetail> OrderDetails
		{
			get
			{
				return this._orderDetails;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class Order
	{
		private int _orderID;
		public virtual int OrderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				this._orderID = value;
			}
		}
		
		private string _customerID;
		public virtual string CustomerID
		{
			get
			{
				return this._customerID;
			}
			set
			{
				this._customerID = value;
			}
		}
		
		private int? _employeeID;
		public virtual int? EmployeeID
		{
			get
			{
				return this._employeeID;
			}
			set
			{
				this._employeeID = value;
			}
		}
		
		private DateTime? _orderDate;
		public virtual DateTime? OrderDate
		{
			get
			{
				return this._orderDate;
			}
			set
			{
				this._orderDate = value;
			}
		}
		
		private DateTime? _requiredDate;
		public virtual DateTime? RequiredDate
		{
			get
			{
				return this._requiredDate;
			}
			set
			{
				this._requiredDate = value;
			}
		}
		
		private DateTime? _shippedDate;
		public virtual DateTime? ShippedDate
		{
			get
			{
				return this._shippedDate;
			}
			set
			{
				this._shippedDate = value;
			}
		}
		
		private int? _shipVia;
		public virtual int? ShipVia
		{
			get
			{
				return this._shipVia;
			}
			set
			{
				this._shipVia = value;
			}
		}
		
		private decimal? _freight;
		public virtual decimal? Freight
		{
			get
			{
				return this._freight;
			}
			set
			{
				this._freight = value;
			}
		}
		
		private string _shipName;
		public virtual string ShipName
		{
			get
			{
				return this._shipName;
			}
			set
			{
				this._shipName = value;
			}
		}
		
		private string _shipAddress;
		public virtual string ShipAddress
		{
			get
			{
				return this._shipAddress;
			}
			set
			{
				this._shipAddress = value;
			}
		}
		
		private string _shipCity;
		public virtual string ShipCity
		{
			get
			{
				return this._shipCity;
			}
			set
			{
				this._shipCity = value;
			}
		}
		
		private string _shipRegion;
		public virtual string ShipRegion
		{
			get
			{
				return this._shipRegion;
			}
			set
			{
				this._shipRegion = value;
			}
		}
		
		private string _shipPostalCode;
		public virtual string ShipPostalCode
		{
			get
			{
				return this._shipPostalCode;
			}
			set
			{
				this._shipPostalCode = value;
			}
		}
		
		private string _shipCountry;
		public virtual string ShipCountry
		{
			get
			{
				return this._shipCountry;
			}
			set
			{
				this._shipCountry = value;
			}
		}
		
		private Customer _customer;
		public virtual Customer Customer
		{
			get
			{
				return this._customer;
			}
			set
			{
				this._customer = value;
			}
		}
		
		private Employee _employee;
		public virtual Employee Employee
		{
			get
			{
				return this._employee;
			}
			set
			{
				this._employee = value;
			}
		}
		
		private Shipper _shipper;
		public virtual Shipper Shipper
		{
			get
			{
				return this._shipper;
			}
			set
			{
				this._shipper = value;
			}
		}
		
		private IList<OrderDetail> _orderDetails = new List<OrderDetail>();
		public virtual IList<OrderDetail> OrderDetails
		{
			get
			{
				return this._orderDetails;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class OrderDetail
	{
		private int _orderID;
		public virtual int OrderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				this._orderID = value;
			}
		}
		
		private int _productID;
		public virtual int ProductID
		{
			get
			{
				return this._productID;
			}
			set
			{
				this._productID = value;
			}
		}
		
		private decimal _unitPrice;
		public virtual decimal UnitPrice
		{
			get
			{
				return this._unitPrice;
			}
			set
			{
				this._unitPrice = value;
			}
		}
		
		private short _quantity;
		public virtual short Quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				this._quantity = value;
			}
		}
		
		private float _discount;
		public virtual float Discount
		{
			get
			{
				return this._discount;
			}
			set
			{
				this._discount = value;
			}
		}
		
		private Order _order;
		public virtual Order Order
		{
			get
			{
				return this._order;
			}
			set
			{
				this._order = value;
			}
		}
		
		private Product _product;
		public virtual Product Product
		{
			get
			{
				return this._product;
			}
			set
			{
				this._product = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class Employee
	{
		private int _employeeID;
		public virtual int EmployeeID
		{
			get
			{
				return this._employeeID;
			}
			set
			{
				this._employeeID = value;
			}
		}
		
		private string _lastName;
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				this._lastName = value;
			}
		}
		
		private string _firstName;
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				this._firstName = value;
			}
		}
		
		private string _title;
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		
		private string _titleOfCourtesy;
		public virtual string TitleOfCourtesy
		{
			get
			{
				return this._titleOfCourtesy;
			}
			set
			{
				this._titleOfCourtesy = value;
			}
		}
		
		private DateTime? _birthDate;
		public virtual DateTime? BirthDate
		{
			get
			{
				return this._birthDate;
			}
			set
			{
				this._birthDate = value;
			}
		}
		
		private DateTime? _hireDate;
		public virtual DateTime? HireDate
		{
			get
			{
				return this._hireDate;
			}
			set
			{
				this._hireDate = value;
			}
		}
		
		private string _address;
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
		private string _region;
		public virtual string Region
		{
			get
			{
				return this._region;
			}
			set
			{
				this._region = value;
			}
		}
		
		private string _postalCode;
		public virtual string PostalCode
		{
			get
			{
				return this._postalCode;
			}
			set
			{
				this._postalCode = value;
			}
		}
		
		private string _country;
		public virtual string Country
		{
			get
			{
				return this._country;
			}
			set
			{
				this._country = value;
			}
		}
		
		private string _homePhone;
		public virtual string HomePhone
		{
			get
			{
				return this._homePhone;
			}
			set
			{
				this._homePhone = value;
			}
		}
		
		private string _extension;
		public virtual string Extension
		{
			get
			{
				return this._extension;
			}
			set
			{
				this._extension = value;
			}
		}
		
		private byte[] _photo;
		public virtual byte[] Photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				this._photo = value;
			}
		}
		
		private string _notes;
		public virtual string Notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				this._notes = value;
			}
		}
		
		private int? _reportsTo;
		public virtual int? ReportsTo
		{
			get
			{
				return this._reportsTo;
			}
			set
			{
				this._reportsTo = value;
			}
		}
		
		private string _photoPath;
		public virtual string PhotoPath
		{
			get
			{
				return this._photoPath;
			}
			set
			{
				this._photoPath = value;
			}
		}
		
		private Employee _employee1;
		public virtual Employee Employee1
		{
			get
			{
				return this._employee1;
			}
			set
			{
				this._employee1 = value;
			}
		}
		
		private IList<Territory> _territories = new List<Territory>();
		public virtual IList<Territory> Territories
		{
			get
			{
				return this._territories;
			}
		}
		
		private IList<Order> _orders = new List<Order>();
		public virtual IList<Order> Orders
		{
			get
			{
				return this._orders;
			}
		}
		
		private IList<Employee> _employees = new List<Employee>();
		public virtual IList<Employee> Employees
		{
			get
			{
				return this._employees;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class Customer
	{
		private string _customerID;
		public virtual string CustomerID
		{
			get
			{
				return this._customerID;
			}
			set
			{
				this._customerID = value;
			}
		}
		
		private string _companyName;
		public virtual string CompanyName
		{
			get
			{
				return this._companyName;
			}
			set
			{
				this._companyName = value;
			}
		}
		
		private string _contactName;
		public virtual string ContactName
		{
			get
			{
				return this._contactName;
			}
			set
			{
				this._contactName = value;
			}
		}
		
		private string _contactTitle;
		public virtual string ContactTitle
		{
			get
			{
				return this._contactTitle;
			}
			set
			{
				this._contactTitle = value;
			}
		}
		
		private string _address;
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
		private string _region;
		public virtual string Region
		{
			get
			{
				return this._region;
			}
			set
			{
				this._region = value;
			}
		}
		
		private string _postalCode;
		public virtual string PostalCode
		{
			get
			{
				return this._postalCode;
			}
			set
			{
				this._postalCode = value;
			}
		}
		
		private string _country;
		public virtual string Country
		{
			get
			{
				return this._country;
			}
			set
			{
				this._country = value;
			}
		}
		
		private string _phone;
		public virtual string Phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				this._phone = value;
			}
		}
		
		private string _fax;
		public virtual string Fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				this._fax = value;
			}
		}
		
		private IList<Order> _orders = new List<Order>();
		public virtual IList<Order> Orders
		{
			get
			{
				return this._orders;
			}
		}
		
		private IList<CustomerDemographic> _customerDemographics = new List<CustomerDemographic>();
		public virtual IList<CustomerDemographic> CustomerDemographics
		{
			get
			{
				return this._customerDemographics;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class CustomerDemographic
	{
		private string _customerTypeID;
		public virtual string CustomerTypeID
		{
			get
			{
				return this._customerTypeID;
			}
			set
			{
				this._customerTypeID = value;
			}
		}
		
		private string _customerDesc;
		public virtual string CustomerDesc
		{
			get
			{
				return this._customerDesc;
			}
			set
			{
				this._customerDesc = value;
			}
		}
		
		private IList<Customer> _customers = new List<Customer>();
		public virtual IList<Customer> Customers
		{
			get
			{
				return this._customers;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class Category
	{
		private int _categoryID;
		public virtual int CategoryID
		{
			get
			{
				return this._categoryID;
			}
			set
			{
				this._categoryID = value;
			}
		}
		
		private string _categoryName;
		public virtual string CategoryName
		{
			get
			{
				return this._categoryName;
			}
			set
			{
				this._categoryName = value;
			}
		}
		
		private string _description;
		public virtual string Description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		
		private byte[] _picture;
		public virtual byte[] Picture
		{
			get
			{
				return this._picture;
			}
			set
			{
				this._picture = value;
			}
		}
		
		private IList<Product> _products = new List<Product>();
		public virtual IList<Product> Products
		{
			get
			{
				return this._products;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class SummaryOfSalesByYear
	{
		private DateTime? _shippedDate;
		public virtual DateTime? ShippedDate
		{
			get
			{
				return this._shippedDate;
			}
			set
			{
				this._shippedDate = value;
			}
		}
		
		private int _orderID;
		public virtual int OrderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				this._orderID = value;
			}
		}
		
		private decimal? _subtotal;
		public virtual decimal? Subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				this._subtotal = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class SummaryOfSalesByQuarter
	{
		private DateTime? _shippedDate;
		public virtual DateTime? ShippedDate
		{
			get
			{
				return this._shippedDate;
			}
			set
			{
				this._shippedDate = value;
			}
		}
		
		private int _orderID;
		public virtual int OrderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				this._orderID = value;
			}
		}
		
		private decimal? _subtotal;
		public virtual decimal? Subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				this._subtotal = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class SalesTotalsByAmount
	{
		private decimal? _saleAmount;
		public virtual decimal? SaleAmount
		{
			get
			{
				return this._saleAmount;
			}
			set
			{
				this._saleAmount = value;
			}
		}
		
		private int _orderID;
		public virtual int OrderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				this._orderID = value;
			}
		}
		
		private string _companyName;
		public virtual string CompanyName
		{
			get
			{
				return this._companyName;
			}
			set
			{
				this._companyName = value;
			}
		}
		
		private DateTime? _shippedDate;
		public virtual DateTime? ShippedDate
		{
			get
			{
				return this._shippedDate;
			}
			set
			{
				this._shippedDate = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class SalesByCategory
	{
		private int _categoryID;
		public virtual int CategoryID
		{
			get
			{
				return this._categoryID;
			}
			set
			{
				this._categoryID = value;
			}
		}
		
		private string _categoryName;
		public virtual string CategoryName
		{
			get
			{
				return this._categoryName;
			}
			set
			{
				this._categoryName = value;
			}
		}
		
		private string _productName;
		public virtual string ProductName
		{
			get
			{
				return this._productName;
			}
			set
			{
				this._productName = value;
			}
		}
		
		private decimal? _productSales;
		public virtual decimal? ProductSales
		{
			get
			{
				return this._productSales;
			}
			set
			{
				this._productSales = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class QuarterlyOrder
	{
		private string _customerID;
		public virtual string CustomerID
		{
			get
			{
				return this._customerID;
			}
			set
			{
				this._customerID = value;
			}
		}
		
		private string _companyName;
		public virtual string CompanyName
		{
			get
			{
				return this._companyName;
			}
			set
			{
				this._companyName = value;
			}
		}
		
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
		private string _country;
		public virtual string Country
		{
			get
			{
				return this._country;
			}
			set
			{
				this._country = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class ProductsByCategory
	{
		private string _categoryName;
		public virtual string CategoryName
		{
			get
			{
				return this._categoryName;
			}
			set
			{
				this._categoryName = value;
			}
		}
		
		private string _productName;
		public virtual string ProductName
		{
			get
			{
				return this._productName;
			}
			set
			{
				this._productName = value;
			}
		}
		
		private string _quantityPerUnit;
		public virtual string QuantityPerUnit
		{
			get
			{
				return this._quantityPerUnit;
			}
			set
			{
				this._quantityPerUnit = value;
			}
		}
		
		private short? _unitsInStock;
		public virtual short? UnitsInStock
		{
			get
			{
				return this._unitsInStock;
			}
			set
			{
				this._unitsInStock = value;
			}
		}
		
		private bool _discontinued;
		public virtual bool Discontinued
		{
			get
			{
				return this._discontinued;
			}
			set
			{
				this._discontinued = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class ProductsAboveAveragePrice
	{
		private string _productName;
		public virtual string ProductName
		{
			get
			{
				return this._productName;
			}
			set
			{
				this._productName = value;
			}
		}
		
		private decimal? _unitPrice;
		public virtual decimal? UnitPrice
		{
			get
			{
				return this._unitPrice;
			}
			set
			{
				this._unitPrice = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class ProductSalesFor1997
	{
		private string _categoryName;
		public virtual string CategoryName
		{
			get
			{
				return this._categoryName;
			}
			set
			{
				this._categoryName = value;
			}
		}
		
		private string _productName;
		public virtual string ProductName
		{
			get
			{
				return this._productName;
			}
			set
			{
				this._productName = value;
			}
		}
		
		private decimal? _productSales;
		public virtual decimal? ProductSales
		{
			get
			{
				return this._productSales;
			}
			set
			{
				this._productSales = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class OrdersQry
	{
		private int _orderID;
		public virtual int OrderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				this._orderID = value;
			}
		}
		
		private string _customerID;
		public virtual string CustomerID
		{
			get
			{
				return this._customerID;
			}
			set
			{
				this._customerID = value;
			}
		}
		
		private int? _employeeID;
		public virtual int? EmployeeID
		{
			get
			{
				return this._employeeID;
			}
			set
			{
				this._employeeID = value;
			}
		}
		
		private DateTime? _orderDate;
		public virtual DateTime? OrderDate
		{
			get
			{
				return this._orderDate;
			}
			set
			{
				this._orderDate = value;
			}
		}
		
		private DateTime? _requiredDate;
		public virtual DateTime? RequiredDate
		{
			get
			{
				return this._requiredDate;
			}
			set
			{
				this._requiredDate = value;
			}
		}
		
		private DateTime? _shippedDate;
		public virtual DateTime? ShippedDate
		{
			get
			{
				return this._shippedDate;
			}
			set
			{
				this._shippedDate = value;
			}
		}
		
		private int? _shipVia;
		public virtual int? ShipVia
		{
			get
			{
				return this._shipVia;
			}
			set
			{
				this._shipVia = value;
			}
		}
		
		private decimal? _freight;
		public virtual decimal? Freight
		{
			get
			{
				return this._freight;
			}
			set
			{
				this._freight = value;
			}
		}
		
		private string _shipName;
		public virtual string ShipName
		{
			get
			{
				return this._shipName;
			}
			set
			{
				this._shipName = value;
			}
		}
		
		private string _shipAddress;
		public virtual string ShipAddress
		{
			get
			{
				return this._shipAddress;
			}
			set
			{
				this._shipAddress = value;
			}
		}
		
		private string _shipCity;
		public virtual string ShipCity
		{
			get
			{
				return this._shipCity;
			}
			set
			{
				this._shipCity = value;
			}
		}
		
		private string _shipRegion;
		public virtual string ShipRegion
		{
			get
			{
				return this._shipRegion;
			}
			set
			{
				this._shipRegion = value;
			}
		}
		
		private string _shipPostalCode;
		public virtual string ShipPostalCode
		{
			get
			{
				return this._shipPostalCode;
			}
			set
			{
				this._shipPostalCode = value;
			}
		}
		
		private string _shipCountry;
		public virtual string ShipCountry
		{
			get
			{
				return this._shipCountry;
			}
			set
			{
				this._shipCountry = value;
			}
		}
		
		private string _companyName;
		public virtual string CompanyName
		{
			get
			{
				return this._companyName;
			}
			set
			{
				this._companyName = value;
			}
		}
		
		private string _address;
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
		private string _region;
		public virtual string Region
		{
			get
			{
				return this._region;
			}
			set
			{
				this._region = value;
			}
		}
		
		private string _postalCode;
		public virtual string PostalCode
		{
			get
			{
				return this._postalCode;
			}
			set
			{
				this._postalCode = value;
			}
		}
		
		private string _country;
		public virtual string Country
		{
			get
			{
				return this._country;
			}
			set
			{
				this._country = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class OrderSubtotal
	{
		private int _orderID;
		public virtual int OrderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				this._orderID = value;
			}
		}
		
		private decimal? _subtotal;
		public virtual decimal? Subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				this._subtotal = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class OrderDetailsExtended
	{
		private int _orderID;
		public virtual int OrderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				this._orderID = value;
			}
		}
		
		private int _productID;
		public virtual int ProductID
		{
			get
			{
				return this._productID;
			}
			set
			{
				this._productID = value;
			}
		}
		
		private string _productName;
		public virtual string ProductName
		{
			get
			{
				return this._productName;
			}
			set
			{
				this._productName = value;
			}
		}
		
		private decimal _unitPrice;
		public virtual decimal UnitPrice
		{
			get
			{
				return this._unitPrice;
			}
			set
			{
				this._unitPrice = value;
			}
		}
		
		private short _quantity;
		public virtual short Quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				this._quantity = value;
			}
		}
		
		private float _discount;
		public virtual float Discount
		{
			get
			{
				return this._discount;
			}
			set
			{
				this._discount = value;
			}
		}
		
		private decimal? _extendedPrice;
		public virtual decimal? ExtendedPrice
		{
			get
			{
				return this._extendedPrice;
			}
			set
			{
				this._extendedPrice = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class Invoice
	{
		private string _shipName;
		public virtual string ShipName
		{
			get
			{
				return this._shipName;
			}
			set
			{
				this._shipName = value;
			}
		}
		
		private string _shipAddress;
		public virtual string ShipAddress
		{
			get
			{
				return this._shipAddress;
			}
			set
			{
				this._shipAddress = value;
			}
		}
		
		private string _shipCity;
		public virtual string ShipCity
		{
			get
			{
				return this._shipCity;
			}
			set
			{
				this._shipCity = value;
			}
		}
		
		private string _shipRegion;
		public virtual string ShipRegion
		{
			get
			{
				return this._shipRegion;
			}
			set
			{
				this._shipRegion = value;
			}
		}
		
		private string _shipPostalCode;
		public virtual string ShipPostalCode
		{
			get
			{
				return this._shipPostalCode;
			}
			set
			{
				this._shipPostalCode = value;
			}
		}
		
		private string _shipCountry;
		public virtual string ShipCountry
		{
			get
			{
				return this._shipCountry;
			}
			set
			{
				this._shipCountry = value;
			}
		}
		
		private string _customerID;
		public virtual string CustomerID
		{
			get
			{
				return this._customerID;
			}
			set
			{
				this._customerID = value;
			}
		}
		
		private string _customerName;
		public virtual string CustomerName
		{
			get
			{
				return this._customerName;
			}
			set
			{
				this._customerName = value;
			}
		}
		
		private string _address;
		public virtual string Address
		{
			get
			{
				return this._address;
			}
			set
			{
				this._address = value;
			}
		}
		
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
		private string _region;
		public virtual string Region
		{
			get
			{
				return this._region;
			}
			set
			{
				this._region = value;
			}
		}
		
		private string _postalCode;
		public virtual string PostalCode
		{
			get
			{
				return this._postalCode;
			}
			set
			{
				this._postalCode = value;
			}
		}
		
		private string _country;
		public virtual string Country
		{
			get
			{
				return this._country;
			}
			set
			{
				this._country = value;
			}
		}
		
		private string _salesperson;
		public virtual string Salesperson
		{
			get
			{
				return this._salesperson;
			}
			set
			{
				this._salesperson = value;
			}
		}
		
		private int _orderID;
		public virtual int OrderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				this._orderID = value;
			}
		}
		
		private DateTime? _orderDate;
		public virtual DateTime? OrderDate
		{
			get
			{
				return this._orderDate;
			}
			set
			{
				this._orderDate = value;
			}
		}
		
		private DateTime? _requiredDate;
		public virtual DateTime? RequiredDate
		{
			get
			{
				return this._requiredDate;
			}
			set
			{
				this._requiredDate = value;
			}
		}
		
		private DateTime? _shippedDate;
		public virtual DateTime? ShippedDate
		{
			get
			{
				return this._shippedDate;
			}
			set
			{
				this._shippedDate = value;
			}
		}
		
		private string _shipperName;
		public virtual string ShipperName
		{
			get
			{
				return this._shipperName;
			}
			set
			{
				this._shipperName = value;
			}
		}
		
		private int _productID;
		public virtual int ProductID
		{
			get
			{
				return this._productID;
			}
			set
			{
				this._productID = value;
			}
		}
		
		private string _productName;
		public virtual string ProductName
		{
			get
			{
				return this._productName;
			}
			set
			{
				this._productName = value;
			}
		}
		
		private decimal _unitPrice;
		public virtual decimal UnitPrice
		{
			get
			{
				return this._unitPrice;
			}
			set
			{
				this._unitPrice = value;
			}
		}
		
		private short _quantity;
		public virtual short Quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				this._quantity = value;
			}
		}
		
		private float _discount;
		public virtual float Discount
		{
			get
			{
				return this._discount;
			}
			set
			{
				this._discount = value;
			}
		}
		
		private decimal? _extendedPrice;
		public virtual decimal? ExtendedPrice
		{
			get
			{
				return this._extendedPrice;
			}
			set
			{
				this._extendedPrice = value;
			}
		}
		
		private decimal? _freight;
		public virtual decimal? Freight
		{
			get
			{
				return this._freight;
			}
			set
			{
				this._freight = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class CustomerAndSuppliersByCity
	{
		private string _city;
		public virtual string City
		{
			get
			{
				return this._city;
			}
			set
			{
				this._city = value;
			}
		}
		
		private string _companyName;
		public virtual string CompanyName
		{
			get
			{
				return this._companyName;
			}
			set
			{
				this._companyName = value;
			}
		}
		
		private string _contactName;
		public virtual string ContactName
		{
			get
			{
				return this._contactName;
			}
			set
			{
				this._contactName = value;
			}
		}
		
		private string _relationship;
		public virtual string Relationship
		{
			get
			{
				return this._relationship;
			}
			set
			{
				this._relationship = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class CurrentProductList
	{
		private int _productID;
		public virtual int ProductID
		{
			get
			{
				return this._productID;
			}
			set
			{
				this._productID = value;
			}
		}
		
		private string _productName;
		public virtual string ProductName
		{
			get
			{
				return this._productName;
			}
			set
			{
				this._productName = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class CategorySalesFor1997
	{
		private string _categoryName;
		public virtual string CategoryName
		{
			get
			{
				return this._categoryName;
			}
			set
			{
				this._categoryName = value;
			}
		}
		
		private decimal? _categorySales;
		public virtual decimal? CategorySales
		{
			get
			{
				return this._categorySales;
			}
			set
			{
				this._categorySales = value;
			}
		}
		
	}
}
namespace Northwind.Data	
{
	public partial class AlphabeticalListOfProduct
	{
		private int _productID;
		public virtual int ProductID
		{
			get
			{
				return this._productID;
			}
			set
			{
				this._productID = value;
			}
		}
		
		private string _productName;
		public virtual string ProductName
		{
			get
			{
				return this._productName;
			}
			set
			{
				this._productName = value;
			}
		}
		
		private int? _supplierID;
		public virtual int? SupplierID
		{
			get
			{
				return this._supplierID;
			}
			set
			{
				this._supplierID = value;
			}
		}
		
		private int? _categoryID;
		public virtual int? CategoryID
		{
			get
			{
				return this._categoryID;
			}
			set
			{
				this._categoryID = value;
			}
		}
		
		private string _quantityPerUnit;
		public virtual string QuantityPerUnit
		{
			get
			{
				return this._quantityPerUnit;
			}
			set
			{
				this._quantityPerUnit = value;
			}
		}
		
		private decimal? _unitPrice;
		public virtual decimal? UnitPrice
		{
			get
			{
				return this._unitPrice;
			}
			set
			{
				this._unitPrice = value;
			}
		}
		
		private short? _unitsInStock;
		public virtual short? UnitsInStock
		{
			get
			{
				return this._unitsInStock;
			}
			set
			{
				this._unitsInStock = value;
			}
		}
		
		private short? _unitsOnOrder;
		public virtual short? UnitsOnOrder
		{
			get
			{
				return this._unitsOnOrder;
			}
			set
			{
				this._unitsOnOrder = value;
			}
		}
		
		private short? _reorderLevel;
		public virtual short? ReorderLevel
		{
			get
			{
				return this._reorderLevel;
			}
			set
			{
				this._reorderLevel = value;
			}
		}
		
		private bool _discontinued;
		public virtual bool Discontinued
		{
			get
			{
				return this._discontinued;
			}
			set
			{
				this._discontinued = value;
			}
		}
		
		private string _categoryName;
		public virtual string CategoryName
		{
			get
			{
				return this._categoryName;
			}
			set
			{
				this._categoryName = value;
			}
		}
		
	}
}
#pragma warning restore 1591
