//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IServiceStringCountWithinString")]
public interface IServiceStringCountWithinString
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStringCountWithinString/GetStringCountWithinString", ReplyAction="http://tempuri.org/IServiceStringCountWithinString/GetStringCountWithinStringResp" +
        "onse")]
    int GetStringCountWithinString(string innerString, string outerString);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServiceStringCountWithinStringChannel : IServiceStringCountWithinString, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServiceStringCountWithinStringClient : System.ServiceModel.ClientBase<IServiceStringCountWithinString>, IServiceStringCountWithinString
{
    
    public ServiceStringCountWithinStringClient()
    {
    }
    
    public ServiceStringCountWithinStringClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceStringCountWithinStringClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceStringCountWithinStringClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceStringCountWithinStringClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetStringCountWithinString(string innerString, string outerString)
    {
        return base.Channel.GetStringCountWithinString(innerString, outerString);
    }
}
