//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateTimeToBulgarianConsole.Client.DayToBulgarianServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DayToBulgarianServiceReference.IServiceDayToBulgarian")]
    public interface IServiceDayToBulgarian {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDayToBulgarian/GetDayInBulgarian", ReplyAction="http://tempuri.org/IServiceDayToBulgarian/GetDayInBulgarianResponse")]
        string GetDayInBulgarian(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDayToBulgarian/GetDayInBulgarian", ReplyAction="http://tempuri.org/IServiceDayToBulgarian/GetDayInBulgarianResponse")]
        System.Threading.Tasks.Task<string> GetDayInBulgarianAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDayToBulgarianChannel : DateTimeToBulgarianConsole.Client.DayToBulgarianServiceReference.IServiceDayToBulgarian, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDayToBulgarianClient : System.ServiceModel.ClientBase<DateTimeToBulgarianConsole.Client.DayToBulgarianServiceReference.IServiceDayToBulgarian>, DateTimeToBulgarianConsole.Client.DayToBulgarianServiceReference.IServiceDayToBulgarian {
        
        public ServiceDayToBulgarianClient() {
        }
        
        public ServiceDayToBulgarianClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDayToBulgarianClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDayToBulgarianClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDayToBulgarianClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayInBulgarian(System.DateTime date) {
            return base.Channel.GetDayInBulgarian(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayInBulgarianAsync(System.DateTime date) {
            return base.Channel.GetDayInBulgarianAsync(date);
        }
    }
}
